// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzrkqxfulzhuxymabdtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cmtxeGZ1bHpodXh5bWFiZHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI4MDEsImV4cCI6MjA2NTQ4ODgwMX0.PFYhObU0hajVtpmNCsOR0q15lxfwfocRiN2BdLLK7Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);